### PR TITLE
added web support

### PR DESCRIPTION
**Pull request by xonaman**

### CODE REVIEW

**Comment by robert-virkus** [comment]
I realize that you're closed the PR, but I still want to thank you for your effort. I believe the approach would  not work, as TCP/IP sockets are not possible on web browsers. So we would need some sort of proxy support, which in turn would result in horrible security implications... Do you agree?

All the best,
   Robert

**Comment by xonaman** [comment]
Yes, you’re right. But if we replace SecureSocket with WebSocketChannel in discovery_helper.dart (which I forgot in the first place, that’s why I closed it), at least the discovery feature would work for the web (which is exactly what I need). Have already implemented and tested this, but not pushed yet. If you like to, I could open another PR with this.

**Comment by robert-virkus** [comment]
Thanks, I think that integrating the whole enough_mail package _just_ for doing discovery on the web is a bit overkikll. Should we move the discovery functionality to another project and make that one available for all platforms?

**Comment by xonaman** [comment]
Good idea. If you don’t mind, I would publish my implementation as mail_discovery and give you credits in the readme.

**Comment by robert-virkus** [comment]
I would rather keep this in the family in case I need to do changes. I have now moved the code here:
https://github.com/Enough-Software/enough_mail_discovery
https://pub.dev/packages/enough_mail_discovery
Demo: https://enough.de/enough_mail_discovery/

**Comment by xonaman** [comment]
Okay, I will create a PR with the web integration in the next few days.

**Comment by robert-virkus** [comment]
Thanks, but note that enough_mail_discovery already supports web.

On non-web platforms more settings can be discovered, specifically when the mail service has not set up any discovery support. In that case several common scenarios are probed, but this can only be done when sockets are supported.

**Comment by xonaman** [comment]
Yes, but if we would use WebSocketChannel on web instead of SecureSocket we could make the „discover more settings“ feature also available on the web. This is what is meant.

**Comment by robert-virkus** [comment]
Sounds exciting, looking forward to test your your approach!

**Comment by robert-virkus** [comment]
AFAIK you cannot connect via web socket to a standard TCP Socket service such as IMAP or SMTP. If you have found a solution for this it would be amazing, so keep up the good work! 😊

**Comment by hatch01** [comment]
Hey, I'd like to implement the possibility to use a web socket proxy in enough mail.
I know it's an enormous potential security issue, so I will add a warning in the documentation and a print at IMAP, SMTP or other client creations. I will also recommend a proxy that is safe or create one myself to be 100% sure of what's in.
Would it be possible to include it in the repo ?

**Comment by hatch01** [comment]
I'd like to use a proxy like :
https://github.com/novnc/websockify
https://github.com/novnc/websockify-other (c version for maximum performance)
https://github.com/aberbegall/dartsockify (to keep dart everywhere)

**Pull request closed without merging**
