### PR TITLE
Support non ascii chars

### PR DESCRIPTION
**Pull request by Mohamed1226**
this branch is support send emails from non ascii domains like "عربي@صيني.انجليزي"

### CODE REVIEW

**Comment by robert-virkus** [comment]
Sorry for the late feedback. I have trouble understanding this PR. I see that you add the "bool supportUnicode" parameter in various places but where is that actually used?

**Comment by Mohamed1226** [comment]
Hello sir,
It used to support sending from non ascii chars domains
 i do that in app support arabic domains like محمد@احمد.اختبار

i used it finally in this command

may be it need to rename but it is so useful

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

في الخميس، ١١ يناير ٢٠٢٤, ٨:٤٨ ص Robert Virkus ***@***.***>
كتب:

**Comment by robert-virkus** [comment]
Thanks, it might be that I will adapt the API a little bit but your change is very welcome!

**Comment by Mohamed1226** [comment]
You're welcome! I appreciate your feedback, and I'm glad to hear that the
change is welcome.

‫في السبت، 20 يناير 2024 في 10:42 ص تمت كتابة ما يلي بواسطة ‪Robert
Virkus‬‏ ***@***.***‬‏>:‬

**Pull request merged**
